// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/rodericusifo/echo-template/internal/app/core/user/resource"
	"github.com/rodericusifo/echo-template/internal/app/repository/database/sql/user"
	"github.com/rodericusifo/echo-template/internal/pkg/util"
)

// Injectors from wire.go:

func UserResource() resource.IUserResource {
	postgresDBSQLConnection := util.GetPostgresDBConnection()
	iUserDatabaseSQLRepository := user.InitPostgresUserDatabaseSQLRepository(postgresDBSQLConnection)
	iUserResource := resource.InitUserResource(iUserDatabaseSQLRepository)
	return iUserResource
}
