// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPayload is an autogenerated mock type for the IPayload type
type IPayload struct {
	mock.Mock
}

// CustomValidatePayload provides a mock function with given fields:
func (_m *IPayload) CustomValidatePayload() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIPayload interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPayload creates a new instance of IPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPayload(t mockConstructorTestingTNewIPayload) *IPayload {
	mock := &IPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
