// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRequestQuery is an autogenerated mock type for the IRequestQuery type
type IRequestQuery struct {
	mock.Mock
}

// CustomValidateRequestQuery provides a mock function with given fields:
func (_m *IRequestQuery) CustomValidateRequestQuery() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIRequestQuery interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRequestQuery creates a new instance of IRequestQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRequestQuery(t mockConstructorTestingTNewIRequestQuery) *IRequestQuery {
	mock := &IRequestQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
