// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRequestUser is an autogenerated mock type for the IRequestUser type
type IRequestUser struct {
	mock.Mock
}

// CustomValidateRequestUser provides a mock function with given fields:
func (_m *IRequestUser) CustomValidateRequestUser() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIRequestUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRequestUser creates a new instance of IRequestUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRequestUser(t mockConstructorTestingTNewIRequestUser) *IRequestUser {
	mock := &IRequestUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
