// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRequestBody is an autogenerated mock type for the IRequestBody type
type IRequestBody struct {
	mock.Mock
}

// CustomValidateRequestBody provides a mock function with given fields:
func (_m *IRequestBody) CustomValidateRequestBody() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIRequestBody interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRequestBody creates a new instance of IRequestBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRequestBody(t mockConstructorTestingTNewIRequestBody) *IRequestBody {
	mock := &IRequestBody{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
