// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	sql "github.com/rodericusifo/echo-template/internal/app/model/database/sql"
	types "github.com/rodericusifo/echo-template/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// IUserDatabaseSQLRepository is an autogenerated mock type for the IUserDatabaseSQLRepository type
type IUserDatabaseSQLRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: payload
func (_m *IUserDatabaseSQLRepository) CreateUser(payload *sql.User) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.User) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: query
func (_m *IUserDatabaseSQLRepository) GetUser(query *types.Query) (*sql.User, error) {
	ret := _m.Called(query)

	var r0 *sql.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.Query) (*sql.User, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(*types.Query) *sql.User); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.Query) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIUserDatabaseSQLRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserDatabaseSQLRepository creates a new instance of IUserDatabaseSQLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserDatabaseSQLRepository(t mockConstructorTestingTNewIUserDatabaseSQLRepository) *IUserDatabaseSQLRepository {
	mock := &IUserDatabaseSQLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
