// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/rodericusifo/echo-template/internal/app/core/auth/service"
	"github.com/rodericusifo/echo-template/internal/app/core/user/resource"
	"github.com/rodericusifo/echo-template/internal/app/repository/database/sql/user"
	"github.com/rodericusifo/echo-template/internal/pkg/util"
)

// Injectors from wire.go:

func AuthService() service.IAuthService {
	postgresDBSQLConnection := util.GetPostgresDBConnection()
	iUserDatabaseSQLRepository := user.InitPostgresUserDatabaseSQLRepository(postgresDBSQLConnection)
	iUserResource := resource.InitUserResource(iUserDatabaseSQLRepository)
	iAuthService := service.InitAuthService(iUserResource)
	return iAuthService
}
